### ISSUE TITLE
How to extract all attachments from an email?

### ISSUE THREAD

**Issue by Anachron** [chneukirchen/mblaze#140]
Yep I can't seem to find that one out. Read `mhdr`, `msed` and alike manuals already.

**Comment by Anachron** [comment]
Forgive me,- duncaen reminded me about https://voidlinux.org/news/2017/12/advent-mblaze-part-2.html
Closing.

**Comment by chneukirchen** [comment]
`mshow -x` will extract all named attachments by default.
