### ISSUE TITLE
New script: mmatt

### ISSUE THREAD

**Issue by Anachron** [chneukirchen/mblaze#143]
Sometimes I send a ton of attachments per mail, mostly for holiday pictures or important documents.
I do this by preparing a file with a list of all attachments that I want to send and then run this little self-written script that just passes them to `mcom` (named it `mmatt` for `[m]blaze [m]ultiple [att]achments`).

```sh
#!/usr/bin/env sh

test -f "${1}" || exit 1
at=$(awk '{print "-attach "$1}' "${1}" | tr '\n' ' ')
mcom ${at}
```
If too simple/useless feel free to close :)

**Comment by chneukirchen** [comment]
I think `mcom -attach $(cat list-if-files)` will work just as well?

**Comment by Anachron** [comment]
Yep, that's totally right, not sure why I didn't think of this. 

Thanks,- closing this!
