### ISSUE TITLE
Compiling on OSX

### ISSUE THREAD

**Issue by larryhynes** [chneukirchen/mblaze#17]
Hi

I don't know if you're interested in supporting OSX. (I'm stuck with it - for now - as my main machine.)

Anyway, OSX doesn't 'have' `clock_gettime`. Using [this patch, for the st terminal emulator](https://gist.github.com/tmsh/8df44a9fcd0180e15906) I am able to get mblaze to compile and run on OSX (I apologise for what I assume is butchery of some scale, but I'm out of my depth), by patching `mgenmid.c` as follows:

```
diff --git a/mgenmid.c b/mgenmid.c
index 7464daa..d3a08fe 100644
--- a/mgenmid.c
+++ b/mgenmid.c
@@ -13,6 +13,20 @@
 
 #include "blaze822.h"
 
+#ifdef __MACH__
+#include <sys/time.h>
+//clock_gettime is not implemented on OSX
+#define CLOCK_MONOTONIC -1
+int clock_gettime(int clk_id /*clk_id*/, struct timespec* t) {
+    struct timeval now;
+    int rv = gettimeofday(&now, NULL);
+    if (rv) return rv;
+    t->tv_sec  = now.tv_sec;
+    t->tv_nsec = now.tv_usec * 1000;
+    return 0;
+}
+#endif
+
 void
 printb36(uint64_t x)
 {
@@ -81,7 +95,7 @@ int main()
 	}
 		
 	struct timespec tp;
-	clock_gettime(CLOCK_REALTIME, &tp);
+	clock_gettime(CLOCK_MONOTONIC, &tp);
 
 	uint64_t rnd;
 ```

**Comment by chneukirchen** [comment]
CLOCK_MONOTONIC is wrong, since i want the wallclock.  Perhaps it would be better to fall back to gettimeofday in this case.

AFAICS MacOS 10.12 has clock_gettime, which version do you use?

**Comment by larryhynes** [comment]
Yosemite (10.10.5). And thanks for the pointer to gettimeofday! (*Hopelessly* out of my depth ;))

**Comment by chneukirchen** [comment]
Actually the code doesn't need the nanosecond precision at all, so we can just always use gettimeofday...

**Comment by larryhynes** [comment]
Brilliant - thanks; that's working locally here now.
