### ISSUE TITLE
message refused: Message is not RFC 2822 compliant

### ISSUE THREAD

**Issue by larryhynes** [chneukirchen/mblaze#20]
OpenSMTPD on OpenBSD 6.0 is rejecting replies to a particular message, with the error:
```
smtp event=failed-command command="DATA" result="550 5.7.1 Delivery not authorized, message refused: Message is not RFC 2822 compliant"
```

I don't *think* there's anything particularly out of the ordinary in the message that I'm trying to send, and replies to this person have been going through today already, so I'm a bit stumped. I'm also aware that debugging this could take a lot of time!

Are there any known 'gotcha' areas regarding RFC compliance and mblaze?

**Comment by larryhynes** [comment]
(I can .tar up the message in question and email it on to you as an attachment if you would like to play with it; there's nothing earth-shaking it there.)

**Comment by chneukirchen** [comment]
Yes, this should not happen. How do you inject the mails? Via OpenBSD smtpd? You can send me the mail to leah@vuxu.org.

**Comment by larryhynes** [comment]
[femail](http://quigon.bsws.de/femail/) as sendmail on localhost -> openbsd smtpd on local gateway -> openbsd smtpd on main server, is the usual route. This mail is getting stopped at the local gateway smtpd i.e femail is passing it on, but opensmtpd is rejecting it. I'll send along a copy of it to you. My reply was just some plain text, [m]imed, then [s]ent.

**Comment by larryhynes** [comment]
(Running smptd with `smtpd -d -vv -T all` doesn't seem to reveal anything beyond that error message, i.e. it doesn't say where or why the message isn't RFC 2822 compliant. :(

**Comment by chneukirchen** [comment]
Reproducible with 

```
mmime <<EOF
References: <aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@a> <bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb@b> <ccccccccccccccccccccccccccccccc@c>

Body
EOF
```

**Comment by chneukirchen** [comment]
Ok, try the new mmime, and please report all issues, i could only test it lightly!

**Comment by larryhynes** [comment]
Great - thanks. It's already passed the first hurdle, and sent the offending message. I'll let you know if there's any further issues.
