### ISSUE TITLE
Specifying address(es) not to be cc'ed

### ISSUE THREAD

**Issue by larryhynes** [chneukirchen/mblaze#26]
This is not an issue, _per se_, it's a 'thinking out loud' exercise; apologies if it gets 'rambly'. It's also not a 'feature request', as I think all the tools are there to handle this already.

In order not to be cc'ed on every mail that I reply to, I've modified `mcom` a wee bit, using `sed` to remove my primary address in `mcom`s `printf Cc:...` line, like so:

```
printf 'Cc: %s\n' "$(mhdr -d -A -h to:cc: "$1" | sed '/larry@larryhynes.com/d' | commajoin)
```

And that is, honestly, as much of a "feature" as I want here and I'm quite happy to stick with this local change. I do wonder, though, if it could be implemented with a `Nocc: user@example.com` header (or headers) in `~/.mblaze/profile`. (Using the full form of the `From:` header probably won't work, as some people will have included me as, for instance, `"Hynes Larry" <larry@larryhynes.com>"`, where my `From:` is `"Larry Hynes" <larry@larryhynes.com>`.)

What _should_ I be doing here, or what are other people doing? Is calling `msed` from `mcom` an option? I mean, I was just manually deleting my address from the `Cc:` line in the message draft, but then I'd forget every now and then, so my current solution is a bit more permanent and a bit more convenient for me.

**Comment by chneukirchen** [comment]
We have a list of `Alternate-Mailboxes:`, and I guess it would make sense to remove these from addressees when replying automatically...

It would also make sense to add a custom hook that changes each mail as you like. :)

**Comment by chneukirchen** [comment]
Actually it doesn't make sense at all to keep our own address from To: in Cc:, so we definitely should filter that one.

**Comment by larryhynes** [comment]
Niceee - thanks. :smile:
