### ISSUE TITLE
Trailing slash on maildir confuses %F in mscan format

### ISSUE THREAD

**Issue by larryhynes** [chneukirchen/mblaze#30]
Hi

When including `%F`in the mscan format string, including a trailing slash on the maildir makes mscan list an empty maildir:

```
$ mlist mail/obsd/ | tail -1 | mscan
 .       Wed  22:07 Reyk Floeter        Re: Arch and vmd
1 mails scanned

$ mlist mail/obsd | tail -1 | mscan
 .      obsd Wed  22:07 Reyk Floeter        Re: Arch and vmd
1 mails scanned
```

```
Scan-Format: %c%u%r %-3n %F %10d %17f %t %2i%s
```

```
 $ mlist mail/obsd/ | tail -1
mail/obsd//cur/1493241609.7408_0.sutro.larryhynes.com:2,T
```

I'm not going to pretend to understand the logic for `%F` in `mscan.c`, but I wonder if we could handle instances of `//` in a path spec. as something other than "". (Or, to come at it from another angle, I wonder does `mlist` have to add a `/` to arguments passed to it, if they already end in `/`.)

**Comment by chneukirchen** [comment]
Should work fine now.

**Comment by larryhynes** [comment]
And so it does - thank you.
