### ISSUE TITLE
PGP/MIME support

### ISSUE THREAD

**Issue by pranomostro** [chneukirchen/mblaze#33]
I hope this is not considered spam here.

Is any PGP/MIME [1][1] [2][2] [3][3] or PGP/Inline support planned in mcom/mrep?
Or would a patch implementing these be accepted either in mcom itself or
as a patch in contrib?

Greetings,

pranomostro

[1]: https://tools.ietf.org/html/rfc1847
[2]: https://tools.ietf.org/html/rfc2015
[3]: https://tools.ietf.org/html/rfc3156

**Comment by chneukirchen** [comment]
I added `contrib/mgpg` to the repo, you can enable it with `multipart/encrypted: mgpg` in filters.
This is for reading only, it works for most encrypted mails I get.

I guess for composing, it would be good to add more menu options (sign, encrypt) for mcom? I'd accept them if they work. :) I guess we should support PGP MIME.

**Comment by pranomostro** [comment]
Ok, great!

I started reading through the different RFCs a bit, but I'm currently
full-time employed, so it may take a while to get stuff done. I'll start
working on it.

**Comment by chneukirchen** [comment]
Perhaps http://faculty.cs.niu.edu/~rickert/mh/ could be interesting.

**Comment by chneukirchen** [comment]
Rough first idea:

```
#!/bin/sh

IFS='
'
FLAGS=$(mhdr -d -A -h from:to:cc:bcc: "$1" |sort -u |sed 's/^/--recipient=/')

printf 'Version: 1\n' >v
awk '/^$/,0' "$1" | mmime | gpg --armor --encrypt $FLAGS >a

{
sed '/^$/q' "$1"
printf '#application/pgp-encrypted v\n'
printf '#application/octet-stream a\n'
} | mmime -t 'multipart/encrypted; protocol="application/pgp-encrypted"'
```

This requires a small patch to mmime to support custom toplevel content types.

**Comment by chneukirchen** [comment]
I added msign and mencrypt now, but this is only barely tested.

mverify only works on whole mails, not as a filter so far, because the filters don't see the headers.

**Comment by pranomostro** [comment]
Ah, sweet.

I will test them and report any bugs.

Thanks for being so quick and responsive. I really like this project.

**Comment by larryhynes** [comment]
(Possibly worth noting that on OS X (Yosemite, at least) `mktemp` by itself fails, it needs something like the full `mktemp -t mgpg.XXXXXX`construct.)

**Comment by chneukirchen** [comment]
Added to mcom now.
