### ISSUE TITLE
Emails with large headers crashes mscan

### ISSUE THREAD

**Issue by mourais** [chneukirchen/mblaze#40]
It looks like any emails with more than 4096 bytes of headers causes mscan to segfault. I have a lot of mail with many "Received" headers and large DKIM keys which go over this limit.

Example crash:

```
Core was generated by `mscan'.
Program terminated with signal 11, Segmentation fault.
[...]
#0  0x0000153f14203b4c in mymemmem (h0=Variable "h0" is not available.
) at mymemmem.c:32
32              for (h++, k--; k; k--, hw = hw<<8 | *++h)
(gdb) bt
#0  0x0000153f14203b4c in mymemmem (h0=Variable "h0" is not available.
) at mymemmem.c:32
#1  0x0000153f14202456 in blaze822 (file=Variable "file" is not available.
) at blaze822.c:361
#2  0x0000153f142013ba in oneline (file=0x1541491dab80 "/tmp/boom.eml")
    at mscan.c:284
#3  0x0000153f14204b9b in blaze822_loop (argc=0, argv=0x1541bda97000,
    cb=0x153f14201360 <oneline>) at seq.c:510
#4  0x0000153f14200dc2 in main (argc=0, argv=0x7f7ffffed768) at mscan.c:565
```

Where "boom.eml" is a file with the line:

`Testing: 1234567890 1234567890 1234567890 1234567890 1234567890`

repeated 64 times

**Comment by chneukirchen** [comment]
I can't reproduce this with a file that has a 7030 char header.

Can you put the file online somewhere? Also please tell OS and architecture.

**Comment by mourais** [comment]
File is here: https://gist.github.com/mourais/0f7d4428f0ddb9fa6640c087afb1dd09

This is on OpenBSD amd64

**Comment by chneukirchen** [comment]
I see. I think it's related to the mail being exactly 4k. Will investigate.

**Comment by chneukirchen** [comment]
Fixed I think.

**Comment by mourais** [comment]
Confirmed, thanks!
