### ISSUE TITLE
Missing manpages

### ISSUE THREAD

**Issue by nbraud** [chneukirchen/mblaze#78]
- [x] `mnext` and `mprev` (likely as part of the `mless` manpage)
- [x] ~`mdate`~
- [x] ~`mquote`~

**Comment by chneukirchen** [comment]
mdate and mquote are mostly for internal use only.

mnext and mprev could be integrated into mless indeed.

**Comment by nbraud** [comment]
OK; would it make sense to move `mdate` and `mquote` to `libexec` (or `lib`, when on a distro that doesn't do `libexec`), then?

**Comment by chneukirchen** [comment]
Not really, because this makes finding the programs harder (also mquote can be overridden by the user)...

**Comment by nbraud** [comment]
Good point.
