### ISSUE TITLE
Use XDG_USER_DIRS when possible?

### ISSUE THREAD

**Issue by josuah** [chneukirchen/mblaze#8]
FreeDesktop.org propose a [standard](https://specifications.freedesktop.org/basedir-spec/latest/) location for configuration files in `~/.config` rather than right away in the `$HOME` directory.

I like to have configuration in some "config" directory ([Rob Pike on dotfiles](https://plus.google.com/+RobPikeTheHuman/posts/R58WgWwN9jp)).

From `mblaze(1)`, I saw `~/.mblaze` as a location for configuration files.

Are you willing to change for `~/.config/mblaze` ?

**Comment by chneukirchen** [comment]
This was adressed in https://github.com/chneukirchen/mblaze/pull/2. Just set `$MBLAZE` as you wish.

**Comment by josuah** [comment]
All right, this will do.

Sorry, I thought there was no issue yet.
