### ISSUE TITLE
[mlist] Use $MAIL variable when no path is specified

### ISSUE THREAD

**Issue by Anachron** [chneukirchen/mblaze#80]
I'd love to see some `$MAIL` usage if I don't pass a folder to `mlist`. 

Other commands could maybe also benefit from this.

**Comment by chneukirchen** [comment]
Such a feature is planned, but I'm not sure which environment variable to use... is `$MAIL` used for maildirs?

**Comment by Anachron** [comment]
Yes, `$MAIL` is meant to be the directory of current users `maildir`. 

https://en.wikibooks.org/wiki/Guide_to_Unix/Environment_Variables#MAIL

**Comment by Duncaen** [comment]
No, `Unix box` == `mbox`, maildir is too new.

**Comment by Anachron** [comment]
Ah, I guess I wouldn't know since I am a `bash`-user.
Thanks for the clarification!

**Comment by Anachron** [comment]
I'm going to write wrapper-scripts, this is not needed anymore.
