### ISSUE TITLE
[mcolor] Rework color used to match themes

### ISSUE THREAD

**Issue by Anachron** [chneukirchen/mblaze#81]
On my custom terminal theme the `mcolor` command looks bad because it uses colors outside the customized range.

An example can be found here:
https://i.imgur.com/aENRzT9.png

I've defined colors like this:
https://github.com/chriskempson/base16-shell/blob/master/scripts/base16-default-dark.sh

**Comment by chneukirchen** [comment]
This looks exactly like it was designed to. ;)

If you don't like the scheme, you can set `MCOLOR_{SEP,FROM,HEADER,FOOTER,SIG,QUOTE,QQUOTE,QQQUOTE}` to any 256-color value you prefer (see the `co` function in mcolor).

**Comment by Anachron** [comment]
@chneukirchen thank you... I wasn't aware that the 16 color space colors are just the beginning of the 256 color space and thus can be easily used via "MCOLOR_<OPT>=1-16".

**Comment by Anachron** [comment]
Sorry I have to reopen since I realized the colors on `mless` are not customizeable (hardcoded):
https://github.com/chneukirchen/mblaze/blob/master/mless#L6-L13
