### ISSUE TITLE
Build fails on GNU/Hurd

### ISSUE THREAD

**Issue by nbraud** [chneukirchen/mblaze#88]
@ucko filed a Debian [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=888398) about mblaze failing to build on Hurd, do to `PATH_MAX` not being defined.

I suggest we either lookup the size via `pathconf`, or default to 4096.
If that's alright by you, I can submit a patch for this.

**Comment by nbraud** [comment]
@chneukirchen f20ca5fa88151efa3edea1eed9a3b08fba9931b7 is not a complete fix: `mdirs.c` references `PATH_MAX` without including `blaze822.h`.

**Comment by chneukirchen** [comment]
Fixed in 3e22345c.
