### ISSUE TITLE
perror on mpick

### ISSUE THREAD

**Issue by josuah** [chneukirchen/mblaze#9]
I get this error while I run this command:

```
$ mlist INBOX | mpick from '~~~' 'amnesty' | mscan
mpick: parse error: invalid string operator at '.addr == 's''
0 mails scanned
```

I also get the same error on other directories (with filtered mails).

Now how can I help with this?

**Comment by Duncaen** [comment]
For test expressions you have to use `-t` like `mpick -t 'from ~~~ "amnesty"'`, without it it tries to use the msglist shortcuts, which are not really ready (and they have a different syntax, you used the expressions not the msglists).

Alternatively you can use `magrep -i from:amnesty`.

**Comment by josuah** [comment]
Yes, sorry I forgot this `-t` option.  I did also try with it: 

```
$ mlist INBOX | mpick -t from '~~~' amnesty
mpick: parse error: invalid string operator at ''
```

I will use `magrep` in the meantime, which works very well!  Thank you for your help.

It is a bit out of topic, but to move mail across maildir inboxes (i.e. from `INBOX` to `amnesty`), do I only have to copy-paste e-mails file from one `cur` directory to the other?

If so, a small note on `mblaze(7)` would have been helpfull, such as:

> You can also use standard coreutils to move or copy mail across mailboxes.

**Comment by Duncaen** [comment]
The -t flag expects just one argument, therefor the expression needs to be escaped.
`mpick -t "from ~~~ \"amnesty\""` or `mpick -t 'from ~~~ "amnesty"'` to avoid escaping.

This makes something like `mpick -t 'from ~~~ "amnesty"' -t 'date < "2017-01-01"'` possible, which would be the same as `mpick -t 'from ~~~ "amnesty" && date < "2017-01-01"'`.

Yes just move mail files around, but this depends a bit on your IMAP client, if it propagates the changes or just redownloads the file you just moved on the next sync.

**Comment by josuah** [comment]
> just one argument

I am sorry, it seems that I can not read and I missed the single quotes.

It does work, no problem.

> just move mail files around

Oh nice, maildir is a great format.

I will propose a change to the man page with an EXAMPLE section, free to refuse of course !  :)

**Comment by josuah** [comment]
In other words, [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK).
